name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Initialize or Deploy App
        run: |
          if [ ! -f "fly.toml" ]; then
            flyctl launch --no-deploy --copy-config --name sandb0x-xtractor --region ord --org personal || true
          fi
          flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
